### ISSUE TITLE
Doesn't handle localized command description

### ISSUE THREAD

**Issue by alexeyr** [piroor/webextensions-lib-shortcut-customize-ui#1]
When I use `"description": "__MSG_NextPageCommand__"`, according to https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Internationalization, I see `__MSG_NextPageCommand__` in the UI instead of the correct description.

Thank you for making this!

**Comment by piroor** [comment]
I recommend you to use this with my another library: https://github.com/piroor/webextensions-lib-l10n

Example in Tree Style Tab addon: https://github.com/piroor/treestyletab/blob/7b369d79cf731fdfdb21b09110a217771b9df902/webextensions/options/init.js#L37

**Comment by piroor** [comment]
Please ignore the previous my comment, now this library resolves such localized labels by self by the commit 68793ee.
