### ISSUE TITLE
Invalid Media Keys

### ISSUE THREAD

**Issue by jerosa** [piroor/webextensions-lib-shortcut-customize-ui#10]
Hi,

First of all thank you for this awesome extension!
A user has reported me that "MediaNextTrack" and "MediaPrevTrack" do not work properly. Unfortunately I do not have a keyboard with those keys so I can not reproduce it.
However I have researched a bit and found [a recent API update](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values#Multimedia_keys) that says the following:

> Internet Explorer, Edge, and Firefox (36 and earlier) use "MediaNextTrack" and "MediaPreviousTrack" instead of "MediaTrackNext" and "MediaTrackPrevious".

Maybe this is the reason why it does not work?

**Comment by piroor** [comment]
Thanks! I missed that and the commit 73c6921 should fix this problem. Could you try again with the latest revision?

**Comment by jerosa** [comment]
Bad news. I tried with the latest revision, using the names I told you but it shows an error.
![imagen](https://user-images.githubusercontent.com/11210989/42169179-4502a448-7e13-11e8-9edc-7dfee8b273ff.png)

Reverting to MediaNextTrack/MediaPrevTrack seems to work for me.
![imagen](https://user-images.githubusercontent.com/11210989/42169489-2b362174-7e14-11e8-9258-bc6a7364a619.png)

However, I log the name of the commands on the console and when I use MediaNextTrack/MediaPrevTrack it shows MediaPlayPause instead.
I suppose it was fine before and it is not working because a Firefox bug?

**Comment by piroor** [comment]
Hmm, it seems a bug of WebExtensions API. Media keys are defined with the name "MediaTrack*" but WebExtensions API detects only "Media*Track" patterns as valid keys.

https://dxr.mozilla.org/mozilla-central/search?q=MediaTrackNext&=mozilla-central
https://dxr.mozilla.org/mozilla-central/search?q=MediaNextTrack&=mozilla-central
https://dxr.mozilla.org/mozilla-esr52/search?q=MediaTrackNext&=mozilla-esr52
https://dxr.mozilla.org/mozilla-esr52/search?q=MediaNextTrack&=mozilla-esr52

**Comment by piroor** [comment]
Now I'm confusing. The document of WebExtensions APIs (and the original document of Google Chrome's extensions APIs) both say that "MediaNextTrack" and "MediaPrevTrack" are acceptable. Codes I referred at the previous comment just respect this spec.
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/commands#Media_keys
https://developer.chrome.com/extensions/commands#usage
So, I need to revert the last change.

Anyway, if those keys don't work as expected, it should be tracked as a bug of Firefox itself.

**Comment by jerosa** [comment]
The docs are confusing indeed. It seems that "MediaNextTrack" and "MediaPrevTrack" are the correct ones. However they don't work.

Sorry for the inconvenience.

**Comment by piroor** [comment]
Sadly I have no keyboard with these media keys, so I cannot test this problem. Could you file a bug to bugzilla.mozilla.org?

**Comment by jerosa** [comment]
Closing this issue because the API is still in development and there is no solution as such. I really appreciate your work, thank you very much.
